import Styles from '@/styles/Contact.module.css';
import Head from 'next/head';
import Header from './Header';
const Contact = () => {
 return (
  <>
   <Head>
    <title>Contact</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
   </Head>
   <Header />
   <br />
   <div className='wrapper'>
    <div className={Styles.container}>
     <h1>Contact Me</h1>
     <p>If you have any questions or feedback, please feel free to reach out at:</p>
     <ul>
      <li>


       <a href="mailto:thakaresagar86@gmail.com">thakaresagar86@gmail.com</a>

      </li>
      <br />
      <li>


       <a href="https://www.linkedin.com/company/example">LinkedIn</a>
      </li>
     </ul>
    </div>
   </div>
  </>
 )
}

export default Contact