import Head from 'next/head'

import styles from '@/styles/Home.module.css'



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>heloow wolrds </div>
        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsam quas autem ipsum enim, tempore nulla explicabo perferendis? Aperiam impedit dolorem, pariatur, fugit neque fugiat quasi iure harum, ut officia adipisci.</p>
      </main>
    </>
  )
}
